name: tests

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:

  run_tests:
    name: Run tests for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Install tox
        run: python3 -m pip install tox tox-gh
      - name: Run unit tests
        run: tox

